= Cloud SDK pass:[<br/>] Visualization pass:[<br/>] カスタマイズガイドライン pass:[<br/>]
:sectnums:
:sectnumlevels: 1
:author: Copyright 2023 Sony Semiconductor Solutions Corporation
:version-label: Version 
:revnumber: x.x.x
:revdate: YYYY - MM - DD
:trademark-desc: AITRIOS™、およびそのロゴは、ソニーグループ株式会社またはその関連会社の登録商標または商標です。
:toc:
:toc-title: 目次
:toclevels: 1
:chapter-label:
:lang: ja

== 更新履歴

|===
|Date |What/Why 

|2023/7/5
|初版作成

|===

== はじめに
本書は、自作したAITaskとWasmを利用した推論結果を可視化する場合に、「**Visualization**」をカスタマイズする手順を説明するものです。 +
Object Detection、Classification、Segmentationの3つのAITaskから、どの形式にするか確認し本書を参照してください。 +
AITaskごとに推論結果がどのように可視化されるかを確認したい場合は、
link:CloudSDK_FuncSpec_Visualization_ja.adoc[**「Cloud SDK Visualization 機能仕様書」**]を参照してください。

== 「**Visualization**」のデシリアライズの流れ
1. `**src/hooks/deserialize/deserializeFunction.ts**` が、選択されているAITaskを識別し、受け取ったデータをデシリアライズする2の処理を呼び出します。

2. `**src/hooks/deserialize/deserializeFunction.ts**` と同階層にある下記ファイルが、FBSファイルから生成されたコードを利用してデシリアライズを行います。
- `**src/hooks/deserialize/deserializeObjectDetection.ts**`
- `**src/hooks/deserialize/deserializeClassification.ts**`
- `**src/hooks/deserialize/deserializeSegmentation.ts**`

3. デシリアライズされたデータは「**Visualization**」の画面上で利用されます。

== 変更の手順・詳細
[#_CodeUpdate]
=== 自動生成コードの作成と配置を行う
1. FBSファイルを元に自動生成コードを作成します。
+ 
手順の詳細はlink:https://github.com/SonySemiconductorSolutions/aitrios-sdk-deserialization-sample/blob/main/docs/development-docs/CloudSDK_Tutorial_DeserializeSample_ja.adoc[**「Cloud SDK Deserialize サンプル チュートリアル」**]を参照してください。
2. 作成したコードで、AITaskごとに所定のディレクトリ内を置き換えます。
+
.AITask毎の格納先ファイルパス
|===
|AITask |ファイルパス 

|Object Detection
|`**src/hooks/deserialize/objectdetection/...**`

|Classification
|`**src/hooks/deserialize/classification/...**`

|Segmentation
|`**src/hooks/deserialize/segmentation/...**`

|===

=== ソースコードを修正する
- 以降の手順で修正しているファイルは、下記表記載のファイルになります。
+
.AITask毎の修正対象ファイル
|===
|AITask |ファイルパス 

|Object Detection
|`**src/hooks/deserialize/deserializeObjectDetection.ts**`

|Classification
|`**src/hooks/deserialize/deserializeClassification.ts**`

|Segmentation
|`**src/hooks/deserialize/deserializeSegmentation.ts**`

|===

==== importするファイルを修正する

1. 自動生成コードを呼び出すファイルを修正します。

- Object Detectionの修正箇所
+
ファイル上部にある下記コードの2~4行目を、自動生成したコードを参照するように修正します。
[source,typescript]
+
----
import * as flatbuffers from 'flatbuffers'
import { ObjectDetectionTop } from './objectdetection/object-detection-top'
import { BoundingBox } from './objectdetection/bounding-box'
import { BoundingBox2d } from './objectdetection/bounding-box2d'
----


- Classificationの修正箇所
+
ファイル上部にある下記コードの2行目を、自動生成したコードを参照するように修正します。
[source,typescript]
+
----
import * as flatbuffers from 'flatbuffers'
import { ClassificationTop } from './classification/classification-top'
----

- Segmentationの修正箇所
+
ファイル上部にある下記コードの2~3行目を、自動生成したコードを参照するように修正します。
[source,typescript]
+
----
import * as flatbuffers from 'flatbuffers'
import { SemanticSegmentationTop } from './segmentation/semantic-segmentation-top'
import { SemanticSegmentationData } from './segmentation/semantic-segmentation-data'
----

==== オブジェクト宣言を修正する
1. 下記に記載されているプロパティ説明を参考に適切な値を代入します。
+
IMPORTANT: プロパティ名を変更するとエラーが発生し正しく動作しなくなります。

- Object Detectionの修正箇所
+
[source,typescript]
----
res = {
  class_id: Number(objList.classId()),
  score,
  left: Number(bbox2d.left()),
  top: Number(bbox2d.top()),
  right: Number(bbox2d.right()),
  bottom: Number(bbox2d.bottom())
}
----
+
|===
|プロパティ名 |説明

|class_id
|推論されたクラスIDを示す数値です。 +
画面上で設定されたラベルと紐づけ、画像上にラベル名を表示するのに利用されます。

|score
|推論確度を示す数値です。 +
画像上に推論結果を描画する際、推論確度として%表記で表示されます。

|left
|Bounding Boxの左辺の座標を示す数値です。 +
画像の上に推論結果を重ねる際に利用されます。

|top
|Bounding Boxの上辺の座標を示す数値です。 +
画像の上に推論結果を重ねる際に利用されます。

|right
|Bounding Boxの右辺の座標を示す数値です。 +
画像の上に推論結果を重ねる際に利用されます。

|bottom
|Bounding Boxの下辺の座標を示す数値です。 +
画像の上に推論結果を重ねる際に利用されます。

|===

- Classificationの修正箇所
+
[source,typescript]
----
res = {
  class_id: Number(clsList.classId()),
  score
}
----
+
|===
|プロパティ名 |説明

|class_id
|推論されたクラスIDを示す数値です。 +
画面上で設定されたラベルと紐づけ、画像表示エリア右側のリストにラベル名を表示するのに利用されます。

|score
|推論確度を示す数値です。 +
画像表示エリア右側のリストに、ラベル名と共に推論確度として%表記で表示されます。

|===

- Segmentationの修正箇所
+
[source,typescript]
----
const deserializedSegmentationData: Inference = {
  height: Number(readsegData.height()),
  width: Number(readsegData.width()),
  classIdMap,
  numClassId: Number(readsegData.numClassId()),
  scoreMap
}
----
+
|===
|プロパティ名 |説明 

|height
|重畳画像の縦幅を示す数値です。 +
重畳画像を生成する際に利用されます。

|width
|重畳画像の横幅を示す数値です。 +
重畳画像を生成する際に利用されます。

|classIdMap
|ピクセル毎の推論された `**class_id**` を示す数値型配列です。 +
重畳画像を生成した後、画面上のラベル設定で色をつけたりする際の対象識別として利用されます。

|numClassId
|推論結果の候補となる `**class_id**` の数を示す数値です。 +
重畳画像を色付けする場合、`**numClassId**` が2以上であれば1ピクセルに複数の推論結果が存在しています。その場合は `**scoreMap**` を `**numClassId**` 分確認し、推論確度の高い方を優先して色付けします。

|scoreMap
|ピクセル毎の推論確度を示す数値型配列です。 +
重畳画像を生成した後、画面上のラベル設定で色をつけたりする際に利用されます。

|===
